add_vhdl_file_to_project $source_folder/fpga_communication/hVHDL_uart/uart_rx/uart_rx_pkg.vhd
add_vhdl_file_to_project $source_folder/fpga_communication/hVHDL_uart/uart_tx/uart_tx_pkg.vhd
add_vhdl_file_to_project $source_folder/fpga_communication/hVHDL_fpga_interconnect/fpga_interconnect_generic_pkg.vhd
add_vhdl_file_to_project $source_folder/fpga_interconnect_pkg.vhd

add_vhdl_file_to_project $source_folder/fpga_communication/communication_protocol_generic_pkg.vhd
add_vhdl_file_to_project $source_folder/fpga_communication/uart_protocol_pkg.vhd
add_vhdl_file_to_project $source_folder/fpga_communication/communications.vhd
