add_vhdl_file_to_project $source_folder/../tubepsu_addresses_pkg.vhd
add_vhdl_file_to_project $source_folder/top/system_clocks_pkg.vhd

add_vhdl_file_to_project $source_folder/dsp/multiplier/multiplier_pkg.vhd 
add_vhdl_file_to_project $source_folder/dsp/multiplier/multiplier_body.vhd
add_vhdl_file_to_project $source_folder/dsp/multiplier/multiplier.vhd     
add_vhdl_file_to_project $source_folder/dsp/sincos/sincos_pkg.vhd         
add_vhdl_file_to_project $source_folder/dsp/sincos/sincos.vhd             

add_vhdl_file_to_project $source_folder/dsp/feedback_control/feedback_control_pkg.vhd
add_vhdl_file_to_project $source_folder/dsp/feedback_control/feedback_control.vhd

add_vhdl_file_to_library $source_folder/common/timing/timing_pkg.vhd                   common_library
add_vhdl_file_to_library $source_folder/common/timing/delay_timer.vhd                  common_library
add_vhdl_file_to_library $source_folder/common/typesdefs/typedefs_pkg.vhd              common_library
add_vhdl_file_to_library $source_folder/common/register_shifts/register_shifts_pkg.vhd common_library

add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/ext_ad/spi3w_ads7056_driver.vhd 
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/ext_ad/ext_ad_spi3w.vhd 

add_vhdl_file_to_library $source_folder/top/system_control/component_interconnect/measurement_interface/onboard_ad_control/onboard_ad_control_pkg.vhd          onboard_adc_library
add_vhdl_file_to_library $source_folder/top/system_control/component_interconnect/measurement_interface/onboard_ad_control/onboard_ad_control_internal_pkg.vhd onboard_adc_library
add_vhdl_file_to_library $source_folder/top/system_control/component_interconnect/measurement_interface/onboard_ad_control/onboard_ad_control.vhd              onboard_adc_library
add_vhdl_file_to_library $source_folder/top/system_control/component_interconnect/measurement_interface/measurement_interface_pkg.vhd                          onboard_adc_library
add_vhdl_file_to_library $source_folder/top/system_control/component_interconnect/measurement_interface/measurement_interface.vhd                              onboard_adc_library
add_vhdl_file_to_library $source_folder/top/system_control/component_interconnect/measurement_interface/psu_measurement_interface_pkg.vhd                      onboard_adc_library

add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_floating_point/float_type_definitions/float_word_length_24_bit_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_floating_point/float_type_definitions/float_type_definitions_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_floating_point/float_arithmetic_operations/float_arithmetic_operations_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_floating_point/normalizer/normalizer_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_floating_point/denormalizer/denormalizer_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_floating_point/float_to_real_conversions/float_to_real_conversions_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_floating_point/float_to_real_conversions/float_to_real_functions_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_floating_point/float_adder/float_adder_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_floating_point/float_multiplier/float_multiplier_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_floating_point/float_alu/float_alu_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_floating_point/float_to_integer_converter/float_to_integer_converter_pkg.vhd

add_vhdl_file_to_project $source_folder/hVHDL_fixed_point/real_to_fixed/real_to_fixed_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_fixed_point/multiplier/configuration/multiply_with_1_input_and_output_registers_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_fixed_point/multiplier/multiplier_base_types_22bit_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_fixed_point/multiplier/multiplier_pkg.vhd

add_vhdl_file_to_project $source_folder/hVHDL_fixed_point/division/division_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_fixed_point/division/division_internal_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_fixed_point/division/division_pkg_body.vhd

add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/processor_configuration/float_processor_ram_width_pkg.vhd

add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_memory_library/multi_port_ram/multi_port_ram_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_memory_library/multi_port_ram/ram_read_x2_write_x1.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_memory_library/multi_port_ram/arch_rtl_read_x2_write_x1.vhd

add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_memory_library/multi_port_ram/ram_read_x4_write_x1.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/source/hVHDL_memory_library/multi_port_ram/arch_rtl_read_x4_write_x1.vhd

add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/processor_configuration/processor_configuration_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/vhdl_assembler/microinstruction_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/vhdl_assembler/float_assembler_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/simple_processor/test_programs_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/processor_configuration/float_pipeline_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/simple_processor/simple_processor_pkg.vhd
add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/memory_processor/memory_processing_pkg.vhd

add_vhdl_file_to_project $source_folder/hVHDL_microprogram_processor/simple_processor/float_example_program_pkg.vhd

add_vhdl_file_to_project $source_folder/../hil_simulation/vhdl_sources/boost/boost_model_pkg.vhd

add_vhdl_file_to_project $source_folder/../hil_simulation/vhdl_sources/boost/boost_rtl_entity.vhd
add_vhdl_file_to_project $source_folder/../hil_simulation/vhdl_sources/boost/current_control/current_control_pkg.vhd
add_vhdl_file_to_project $source_folder/../hil_simulation/vhdl_sources/boost/voltage_control/voltage_control_pkg.vhd

add_vhdl_file_to_project $source_folder/top/system_control/led_driver/led_driver_pkg.vhd 
add_vhdl_file_to_project $source_folder/top/system_control/led_driver/led_driver.vhd 

add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/dhb_control/phase_modulator/deadtime_pkg.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/dhb_control/phase_modulator/deadtime.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/dhb_control/phase_modulator/phase_modulator_pkg.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/dhb_control/phase_modulator/phase_modulator.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/dhb_control/dhb_control_pkg.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/dhb_control/dhb_control.vhd

add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/llc_control/llc_modulator/llc_modulator_pkg.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/llc_control/llc_modulator/llc_modulator.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/llc_control/llc_control_pkg.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/llc_control/llc_control_internal_pkg.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/llc_control/arch_llc_pi_control.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/llc_control/llc_control.vhd

add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/pfc_control/pfc_modulator/pfc_modulator_pkg.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/pfc_control/pfc_modulator/pfc_modulator.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/pfc_control/pfc_control_pkg.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/pfc_control/arch_pfc_current_control.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/pfc_control/arch_pfc_voltage_control.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/pfc_control/pfc_control.vhd

add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/power_supply_control_pkg.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/power_supply_control/power_supply_control.vhd

add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/component_interconnect_pkg.vhd
add_vhdl_file_to_project $source_folder/top/system_control/component_interconnect/component_interconnect.vhd

add_vhdl_file_to_project $source_folder/top/system_control/system_control_pkg.vhd 
add_vhdl_file_to_project $source_folder/top/system_control/system_control_internal_pkg.vhd 
add_vhdl_file_to_project $source_folder/top/system_control/system_control.vhd 
