-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4
-- Module  Version: 4.2
--C:\Programs\diamond\diamond\3.11_x64\ispfpga\bin\nt64\scuba.exe -w -n mpy18x18 -lang vhdl -synth synplify -bus_exp 7 -bb -arch sa5p00 -type dspmult -widtha 18 -widthb 18 -widthp 36 -area -signed -enable_sync -fdc C:/Users/Jari/mycodeprojects/tube_psu/lfe5u/ecp5u_specifics/ecp5_ip_components/mpy18x18/mpy18x18.fdc 

-- Tue Jul 09 22:15:02 2019

library IEEE;
use IEEE.std_logic_1164.all;
library ECP5U;
use ECP5U.components.all;

entity mpy18x18 is
    port (
        A: in  std_logic_vector(17 downto 0); 
        B: in  std_logic_vector(17 downto 0); 
        P: out  std_logic_vector(35 downto 0));
end mpy18x18;

architecture Structure of mpy18x18 is

    -- internal signal declarations
    signal mpy18x18_mult_direct_out_1_35: std_logic;
    signal mpy18x18_mult_direct_out_1_34: std_logic;
    signal mpy18x18_mult_direct_out_1_33: std_logic;
    signal mpy18x18_mult_direct_out_1_32: std_logic;
    signal mpy18x18_mult_direct_out_1_31: std_logic;
    signal mpy18x18_mult_direct_out_1_30: std_logic;
    signal mpy18x18_mult_direct_out_1_29: std_logic;
    signal mpy18x18_mult_direct_out_1_28: std_logic;
    signal mpy18x18_mult_direct_out_1_27: std_logic;
    signal mpy18x18_mult_direct_out_1_26: std_logic;
    signal mpy18x18_mult_direct_out_1_25: std_logic;
    signal mpy18x18_mult_direct_out_1_24: std_logic;
    signal mpy18x18_mult_direct_out_1_23: std_logic;
    signal mpy18x18_mult_direct_out_1_22: std_logic;
    signal mpy18x18_mult_direct_out_1_21: std_logic;
    signal mpy18x18_mult_direct_out_1_20: std_logic;
    signal mpy18x18_mult_direct_out_1_19: std_logic;
    signal mpy18x18_mult_direct_out_1_18: std_logic;
    signal mpy18x18_mult_direct_out_1_17: std_logic;
    signal mpy18x18_mult_direct_out_1_16: std_logic;
    signal mpy18x18_mult_direct_out_1_15: std_logic;
    signal mpy18x18_mult_direct_out_1_14: std_logic;
    signal mpy18x18_mult_direct_out_1_13: std_logic;
    signal mpy18x18_mult_direct_out_1_12: std_logic;
    signal mpy18x18_mult_direct_out_1_11: std_logic;
    signal mpy18x18_mult_direct_out_1_10: std_logic;
    signal mpy18x18_mult_direct_out_1_9: std_logic;
    signal mpy18x18_mult_direct_out_1_8: std_logic;
    signal mpy18x18_mult_direct_out_1_7: std_logic;
    signal mpy18x18_mult_direct_out_1_6: std_logic;
    signal mpy18x18_mult_direct_out_1_5: std_logic;
    signal mpy18x18_mult_direct_out_1_4: std_logic;
    signal mpy18x18_mult_direct_out_1_3: std_logic;
    signal mpy18x18_mult_direct_out_1_2: std_logic;
    signal mpy18x18_mult_direct_out_1_1: std_logic;
    signal mpy18x18_mult_direct_out_1_0: std_logic;
    signal scuba_vhi: std_logic;
    signal scuba_vlo: std_logic;

    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    dsp_mult_0: MULT18X18D
        generic map (CLK3_DIV=> "ENABLED", CLK2_DIV=> "ENABLED", 
        CLK1_DIV=> "ENABLED", CLK0_DIV=> "ENABLED", HIGHSPEED_CLK=> "NONE", 
        REG_INPUTC_RST=> "RST0", REG_INPUTC_CE=> "CE0", REG_INPUTC_CLK=> "NONE", 
        SOURCEB_MODE=> "B_SHIFT", MULT_BYPASS=> "DISABLED", 
        CAS_MATCH_REG=> "FALSE", RESETMODE=> "SYNC", GSR=> "ENABLED", 
        REG_OUTPUT_RST=> "RST0", REG_OUTPUT_CE=> "CE0", REG_OUTPUT_CLK=> "NONE", 
        REG_PIPELINE_RST=> "RST0", REG_PIPELINE_CE=> "CE0", 
        REG_PIPELINE_CLK=> "NONE", REG_INPUTB_RST=> "RST0", 
        REG_INPUTB_CE=> "CE0", REG_INPUTB_CLK=> "NONE", REG_INPUTA_RST=> "RST0", 
        REG_INPUTA_CE=> "CE0", REG_INPUTA_CLK=> "NONE")
        port map (A17=>A(17), A16=>A(16), A15=>A(15), A14=>A(14), 
            A13=>A(13), A12=>A(12), A11=>A(11), A10=>A(10), A9=>A(9), 
            A8=>A(8), A7=>A(7), A6=>A(6), A5=>A(5), A4=>A(4), A3=>A(3), 
            A2=>A(2), A1=>A(1), A0=>A(0), B17=>B(17), B16=>B(16), 
            B15=>B(15), B14=>B(14), B13=>B(13), B12=>B(12), B11=>B(11), 
            B10=>B(10), B9=>B(9), B8=>B(8), B7=>B(7), B6=>B(6), B5=>B(5), 
            B4=>B(4), B3=>B(3), B2=>B(2), B1=>B(1), B0=>B(0), 
            C17=>scuba_vlo, C16=>scuba_vlo, C15=>scuba_vlo, 
            C14=>scuba_vlo, C13=>scuba_vlo, C12=>scuba_vlo, 
            C11=>scuba_vlo, C10=>scuba_vlo, C9=>scuba_vlo, C8=>scuba_vlo, 
            C7=>scuba_vlo, C6=>scuba_vlo, C5=>scuba_vlo, C4=>scuba_vlo, 
            C3=>scuba_vlo, C2=>scuba_vlo, C1=>scuba_vlo, C0=>scuba_vlo, 
            SIGNEDA=>scuba_vhi, SIGNEDB=>scuba_vhi, SOURCEA=>scuba_vlo, 
            SOURCEB=>scuba_vlo, CE0=>scuba_vhi, CE1=>scuba_vhi, 
            CE2=>scuba_vhi, CE3=>scuba_vhi, CLK0=>scuba_vlo, 
            CLK1=>scuba_vlo, CLK2=>scuba_vlo, CLK3=>scuba_vlo, 
            RST0=>scuba_vlo, RST1=>scuba_vlo, RST2=>scuba_vlo, 
            RST3=>scuba_vlo, SRIA17=>scuba_vlo, SRIA16=>scuba_vlo, 
            SRIA15=>scuba_vlo, SRIA14=>scuba_vlo, SRIA13=>scuba_vlo, 
            SRIA12=>scuba_vlo, SRIA11=>scuba_vlo, SRIA10=>scuba_vlo, 
            SRIA9=>scuba_vlo, SRIA8=>scuba_vlo, SRIA7=>scuba_vlo, 
            SRIA6=>scuba_vlo, SRIA5=>scuba_vlo, SRIA4=>scuba_vlo, 
            SRIA3=>scuba_vlo, SRIA2=>scuba_vlo, SRIA1=>scuba_vlo, 
            SRIA0=>scuba_vlo, SRIB17=>scuba_vlo, SRIB16=>scuba_vlo, 
            SRIB15=>scuba_vlo, SRIB14=>scuba_vlo, SRIB13=>scuba_vlo, 
            SRIB12=>scuba_vlo, SRIB11=>scuba_vlo, SRIB10=>scuba_vlo, 
            SRIB9=>scuba_vlo, SRIB8=>scuba_vlo, SRIB7=>scuba_vlo, 
            SRIB6=>scuba_vlo, SRIB5=>scuba_vlo, SRIB4=>scuba_vlo, 
            SRIB3=>scuba_vlo, SRIB2=>scuba_vlo, SRIB1=>scuba_vlo, 
            SRIB0=>scuba_vlo, SROA17=>open, SROA16=>open, SROA15=>open, 
            SROA14=>open, SROA13=>open, SROA12=>open, SROA11=>open, 
            SROA10=>open, SROA9=>open, SROA8=>open, SROA7=>open, 
            SROA6=>open, SROA5=>open, SROA4=>open, SROA3=>open, 
            SROA2=>open, SROA1=>open, SROA0=>open, SROB17=>open, 
            SROB16=>open, SROB15=>open, SROB14=>open, SROB13=>open, 
            SROB12=>open, SROB11=>open, SROB10=>open, SROB9=>open, 
            SROB8=>open, SROB7=>open, SROB6=>open, SROB5=>open, 
            SROB4=>open, SROB3=>open, SROB2=>open, SROB1=>open, 
            SROB0=>open, ROA17=>open, ROA16=>open, ROA15=>open, 
            ROA14=>open, ROA13=>open, ROA12=>open, ROA11=>open, 
            ROA10=>open, ROA9=>open, ROA8=>open, ROA7=>open, ROA6=>open, 
            ROA5=>open, ROA4=>open, ROA3=>open, ROA2=>open, ROA1=>open, 
            ROA0=>open, ROB17=>open, ROB16=>open, ROB15=>open, 
            ROB14=>open, ROB13=>open, ROB12=>open, ROB11=>open, 
            ROB10=>open, ROB9=>open, ROB8=>open, ROB7=>open, ROB6=>open, 
            ROB5=>open, ROB4=>open, ROB3=>open, ROB2=>open, ROB1=>open, 
            ROB0=>open, ROC17=>open, ROC16=>open, ROC15=>open, 
            ROC14=>open, ROC13=>open, ROC12=>open, ROC11=>open, 
            ROC10=>open, ROC9=>open, ROC8=>open, ROC7=>open, ROC6=>open, 
            ROC5=>open, ROC4=>open, ROC3=>open, ROC2=>open, ROC1=>open, 
            ROC0=>open, P35=>mpy18x18_mult_direct_out_1_35, 
            P34=>mpy18x18_mult_direct_out_1_34, 
            P33=>mpy18x18_mult_direct_out_1_33, 
            P32=>mpy18x18_mult_direct_out_1_32, 
            P31=>mpy18x18_mult_direct_out_1_31, 
            P30=>mpy18x18_mult_direct_out_1_30, 
            P29=>mpy18x18_mult_direct_out_1_29, 
            P28=>mpy18x18_mult_direct_out_1_28, 
            P27=>mpy18x18_mult_direct_out_1_27, 
            P26=>mpy18x18_mult_direct_out_1_26, 
            P25=>mpy18x18_mult_direct_out_1_25, 
            P24=>mpy18x18_mult_direct_out_1_24, 
            P23=>mpy18x18_mult_direct_out_1_23, 
            P22=>mpy18x18_mult_direct_out_1_22, 
            P21=>mpy18x18_mult_direct_out_1_21, 
            P20=>mpy18x18_mult_direct_out_1_20, 
            P19=>mpy18x18_mult_direct_out_1_19, 
            P18=>mpy18x18_mult_direct_out_1_18, 
            P17=>mpy18x18_mult_direct_out_1_17, 
            P16=>mpy18x18_mult_direct_out_1_16, 
            P15=>mpy18x18_mult_direct_out_1_15, 
            P14=>mpy18x18_mult_direct_out_1_14, 
            P13=>mpy18x18_mult_direct_out_1_13, 
            P12=>mpy18x18_mult_direct_out_1_12, 
            P11=>mpy18x18_mult_direct_out_1_11, 
            P10=>mpy18x18_mult_direct_out_1_10, 
            P9=>mpy18x18_mult_direct_out_1_9, 
            P8=>mpy18x18_mult_direct_out_1_8, 
            P7=>mpy18x18_mult_direct_out_1_7, 
            P6=>mpy18x18_mult_direct_out_1_6, 
            P5=>mpy18x18_mult_direct_out_1_5, 
            P4=>mpy18x18_mult_direct_out_1_4, 
            P3=>mpy18x18_mult_direct_out_1_3, 
            P2=>mpy18x18_mult_direct_out_1_2, 
            P1=>mpy18x18_mult_direct_out_1_1, 
            P0=>mpy18x18_mult_direct_out_1_0, SIGNEDP=>open);

    P(35) <= mpy18x18_mult_direct_out_1_35;
    P(34) <= mpy18x18_mult_direct_out_1_34;
    P(33) <= mpy18x18_mult_direct_out_1_33;
    P(32) <= mpy18x18_mult_direct_out_1_32;
    P(31) <= mpy18x18_mult_direct_out_1_31;
    P(30) <= mpy18x18_mult_direct_out_1_30;
    P(29) <= mpy18x18_mult_direct_out_1_29;
    P(28) <= mpy18x18_mult_direct_out_1_28;
    P(27) <= mpy18x18_mult_direct_out_1_27;
    P(26) <= mpy18x18_mult_direct_out_1_26;
    P(25) <= mpy18x18_mult_direct_out_1_25;
    P(24) <= mpy18x18_mult_direct_out_1_24;
    P(23) <= mpy18x18_mult_direct_out_1_23;
    P(22) <= mpy18x18_mult_direct_out_1_22;
    P(21) <= mpy18x18_mult_direct_out_1_21;
    P(20) <= mpy18x18_mult_direct_out_1_20;
    P(19) <= mpy18x18_mult_direct_out_1_19;
    P(18) <= mpy18x18_mult_direct_out_1_18;
    P(17) <= mpy18x18_mult_direct_out_1_17;
    P(16) <= mpy18x18_mult_direct_out_1_16;
    P(15) <= mpy18x18_mult_direct_out_1_15;
    P(14) <= mpy18x18_mult_direct_out_1_14;
    P(13) <= mpy18x18_mult_direct_out_1_13;
    P(12) <= mpy18x18_mult_direct_out_1_12;
    P(11) <= mpy18x18_mult_direct_out_1_11;
    P(10) <= mpy18x18_mult_direct_out_1_10;
    P(9) <= mpy18x18_mult_direct_out_1_9;
    P(8) <= mpy18x18_mult_direct_out_1_8;
    P(7) <= mpy18x18_mult_direct_out_1_7;
    P(6) <= mpy18x18_mult_direct_out_1_6;
    P(5) <= mpy18x18_mult_direct_out_1_5;
    P(4) <= mpy18x18_mult_direct_out_1_4;
    P(3) <= mpy18x18_mult_direct_out_1_3;
    P(2) <= mpy18x18_mult_direct_out_1_2;
    P(1) <= mpy18x18_mult_direct_out_1_1;
    P(0) <= mpy18x18_mult_direct_out_1_0;
end Structure;
