-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.0.396.4
-- Module  Version: 4.2
-- Tue Jul 09 22:15:02 2019

-- parameterized module component declaration
component mpy18x18
    port (A: in  std_logic_vector(17 downto 0); 
        B: in  std_logic_vector(17 downto 0); 
        P: out  std_logic_vector(35 downto 0));
end component;

-- parameterized module component instance
__ : mpy18x18
    port map (A(17 downto 0)=>__, B(17 downto 0)=>__, P(35 downto 0)=>__);
