-- VHDL testbench template generated by SCUBA Diamond (64-bit) 3.11.0.396.4
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.std_logic_unsigned.all;

use IEEE.math_real.all;

use IEEE.numeric_std.all;

entity tb is
end entity tb;


architecture test of tb is 

    component mpy18x18
        port (A : in std_logic_vector(17 downto 0); 
        B : in std_logic_vector(17 downto 0); 
        P : out std_logic_vector(35 downto 0)
    );
    end component;

    signal A : std_logic_vector(17 downto 0) := (others => '0');
    signal B : std_logic_vector(17 downto 0) := (others => '0');
    signal P : std_logic_vector(35 downto 0);
begin
    u1 : mpy18x18
        port map (A => A, B => B, P => P
        );

    process

    begin
      A <= (others => '0') ;
      for i in 0 to 200 loop
        wait for 10 ns;
        A <= A + '1' ;
      end loop;
      wait;
    end process;

    process

    begin
      B <= (others => '0') ;
      for i in 0 to 200 loop
        wait for 10 ns;
        B <= B + '1' ;
      end loop;
      wait;
    end process;

end architecture test;
