
####################################################################################
# Generated by Vivado 2019.1 built on 'Fri May 24 14:49:42 MDT 2019' by 'xbuild'
# Command Used: write_xdc -force C:/Users/Jari/mycodeprojects/tube_psu/spartan_7/constraints/constraints.xdc
####################################################################################


####################################################################################
# Constraints from file : 'main_pll_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'main_pll.xdc'
####################################################################################


# file: main_pll.xdc
#
# (c) Copyright 2008 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.
#

# Input clock periods. These duplicate the values entered for the
# input clocks. You can use these to time your system. If required
# commented constraints can be used in the top level xdc
#----------------------------------------------------------------
# Connect to input port when clock capable pin is selected for input
create_clock -period 31.250 [get_ports xclk32mhz]
set_input_jitter [get_clocks -of_objects [get_ports xclk32mhz]] 0.313


current_instance core_clocks/inst
set_property PHASESHIFT_MODE WAVEFORM [get_cells -hierarchical *adv*]


####################################################################################
# Constraints from file : 'constraints.xdc'
####################################################################################


####################################################################################
# Generated by Vivado 2019.1 built on 'Fri May 24 14:49:42 MDT 2019' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'main_pll_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'main_pll.xdc'
####################################################################################


# file: main_pll.xdc
#
# (c) Copyright 2008 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.
#

# Input clock periods. These duplicate the values entered for the
# input clocks. You can use these to time your system. If required
# commented constraints can be used in the top level xdc
#----------------------------------------------------------------
# Connect to input port when clock capable pin is selected for input
current_instance -quiet
create_clock -period 31.250 [get_ports xclk32mhz]
set_input_jitter [get_clocks -of_objects [get_ports xclk32mhz]] 0.313


current_instance core_clocks/inst
set_property PHASESHIFT_MODE WAVEFORM [get_cells -hierarchical *adv*]


####################################################################################
# Constraints from file : 'constraints.xdc'
####################################################################################


####################################################################################
# Generated by Vivado 2019.1 built on 'Fri May 24 14:49:42 MDT 2019' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'main_pll_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'main_pll.xdc'
####################################################################################


# file: main_pll.xdc
#
# (c) Copyright 2008 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.
#

# Input clock periods. These duplicate the values entered for the
# input clocks. You can use these to time your system. If required
# commented constraints can be used in the top level xdc
#----------------------------------------------------------------
# Connect to input port when clock capable pin is selected for input
current_instance -quiet
create_clock -period 31.250 [get_ports xclk32mhz]
set_input_jitter [get_clocks -of_objects [get_ports xclk32mhz]] 0.313


current_instance core_clocks/inst
set_property PHASESHIFT_MODE WAVEFORM [get_cells -hierarchical *adv*]


####################################################################################
# Constraints from file : 'pinouts.xdc'
####################################################################################


####################################################################################
# Generated by Vivado 2019.1 built on 'Fri May 24 14:49:42 MDT 2019' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'main_pll_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'main_pll.xdc'
####################################################################################


# file: main_pll.xdc
#
# (c) Copyright 2008 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.
#

# Input clock periods. These duplicate the values entered for the
# input clocks. You can use these to time your system. If required
# commented constraints can be used in the top level xdc
#----------------------------------------------------------------
# Connect to input port when clock capable pin is selected for input
current_instance -quiet
create_clock -period 31.250 [get_ports xclk32mhz]
set_input_jitter [get_clocks -of_objects [get_ports xclk32mhz]] 0.313


current_instance core_clocks/inst
set_property PHASESHIFT_MODE WAVEFORM [get_cells -hierarchical *adv*]


# User Generated IO constraints

current_instance -quiet
set_property IOSTANDARD LVCMOS33 [get_ports {po2_DHB_pri_pwm[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po2_DHB_pri_pwm[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po2_DHB_sec_pwm[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po2_DHB_sec_pwm[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po2_ht_pri_pwm[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po2_ht_pri_pwm[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po2_ht_sec_pwm[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po2_ht_sec_pwm[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po2_pfc_pwm[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po2_pfc_pwm[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_ada_muxsel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_ada_muxsel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_ada_muxsel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_adb_muxsel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_adb_muxsel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_adb_muxsel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_led1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_led1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_led1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_led2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_led2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_led2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_led3[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_led3[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {po3_led3[0]}]
set_property DRIVE 4 [get_ports {po2_DHB_pri_pwm[1]}]
set_property DRIVE 4 [get_ports {po2_DHB_pri_pwm[0]}]
set_property DRIVE 4 [get_ports {po2_DHB_sec_pwm[1]}]
set_property DRIVE 4 [get_ports {po2_DHB_sec_pwm[0]}]
set_property DRIVE 4 [get_ports {po2_ht_pri_pwm[1]}]
set_property DRIVE 4 [get_ports {po2_ht_pri_pwm[0]}]
set_property DRIVE 4 [get_ports {po2_ht_sec_pwm[1]}]
set_property DRIVE 4 [get_ports {po2_ht_sec_pwm[0]}]
set_property DRIVE 4 [get_ports {po2_pfc_pwm[1]}]
set_property DRIVE 4 [get_ports {po2_pfc_pwm[0]}]
set_property DRIVE 4 [get_ports {po3_ada_muxsel[2]}]
set_property DRIVE 4 [get_ports {po3_ada_muxsel[1]}]
set_property DRIVE 4 [get_ports {po3_ada_muxsel[0]}]
set_property DRIVE 4 [get_ports {po3_adb_muxsel[2]}]
set_property DRIVE 4 [get_ports {po3_adb_muxsel[1]}]
set_property DRIVE 4 [get_ports {po3_adb_muxsel[0]}]
set_property DRIVE 8 [get_ports {po3_led1[2]}]
set_property DRIVE 8 [get_ports {po3_led1[1]}]
set_property DRIVE 8 [get_ports {po3_led1[0]}]
set_property DRIVE 8 [get_ports {po3_led2[2]}]
set_property DRIVE 8 [get_ports {po3_led2[1]}]
set_property DRIVE 8 [get_ports {po3_led2[0]}]
set_property DRIVE 8 [get_ports {po3_led3[2]}]
set_property DRIVE 8 [get_ports {po3_led3[1]}]
set_property DRIVE 8 [get_ports {po3_led3[0]}]




# User Generated physical constraints

set_property PACKAGE_PIN H11 [get_ports xclk32mhz]

# User Generated IO constraints

set_property IOSTANDARD LVCMOS33 [get_ports pi_ada_sdata]
set_property IOSTANDARD LVCMOS33 [get_ports pi_adb_sdata]
set_property IOSTANDARD LVCMOS33 [get_ports pi_ext_ad1_sdata]
set_property IOSTANDARD LVCMOS33 [get_ports pi_ext_ad2_sdata]
set_property IOSTANDARD LVCMOS33 [get_ports pi_uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports po_ada_clk]
set_property IOSTANDARD LVCMOS33 [get_ports po_ada_cs]
set_property IOSTANDARD LVCMOS33 [get_ports po_adb_clk]
set_property IOSTANDARD LVCMOS33 [get_ports po_adb_cs]
set_property IOSTANDARD LVCMOS33 [get_ports po_bypass_relay]
set_property IOSTANDARD LVCMOS33 [get_ports po_ext_ad1_clk]
set_property IOSTANDARD LVCMOS33 [get_ports po_ext_ad1_cs]
set_property IOSTANDARD LVCMOS33 [get_ports po_ext_ad2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports po_ext_ad2_cs]
set_property IOSTANDARD LVCMOS33 [get_ports po_uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports xclk32mhz]

# User Generated physical constraints

set_property PACKAGE_PIN A13 [get_ports po_ada_clk]
set_property PACKAGE_PIN B14 [get_ports po_ada_cs]
set_property PACKAGE_PIN D14 [get_ports po_adb_clk]
set_property PACKAGE_PIN E13 [get_ports po_adb_cs]
set_property PACKAGE_PIN C14 [get_ports pi_ada_sdata]
set_property PACKAGE_PIN F13 [get_ports pi_adb_sdata]
set_property PACKAGE_PIN J13 [get_ports {po3_led3[0]}]
set_property PACKAGE_PIN L14 [get_ports {po3_led3[1]}]
set_property PACKAGE_PIN J14 [get_ports {po3_led3[2]}]
set_property PACKAGE_PIN H13 [get_ports {po3_led2[2]}]
set_property PACKAGE_PIN D13 [get_ports {po3_led1[2]}]
set_property PACKAGE_PIN G14 [get_ports {po3_led1[1]}]
set_property PACKAGE_PIN F14 [get_ports {po3_led1[0]}]
set_property PACKAGE_PIN B6 [get_ports {po3_adb_muxsel[0]}]
set_property PACKAGE_PIN A5 [get_ports {po3_adb_muxsel[1]}]
set_property PACKAGE_PIN B5 [get_ports {po3_adb_muxsel[2]}]
set_property PACKAGE_PIN B13 [get_ports {po3_ada_muxsel[0]}]
set_property PACKAGE_PIN A12 [get_ports {po3_ada_muxsel[1]}]
set_property PACKAGE_PIN A10 [get_ports {po3_ada_muxsel[2]}]
set_property PACKAGE_PIN H1 [get_ports po_bypass_relay]
set_property PACKAGE_PIN D2 [get_ports po_uart_tx]
set_property PACKAGE_PIN E2 [get_ports pi_uart_rx]
set_property PACKAGE_PIN P2 [get_ports po_ext_ad1_cs]
set_property PACKAGE_PIN L2 [get_ports pi_ext_ad1_sdata]
set_property PACKAGE_PIN J1 [get_ports po_ext_ad1_clk]
set_property PACKAGE_PIN L1 [get_ports po_ext_ad2_clk]
set_property PACKAGE_PIN M3 [get_ports po_ext_ad2_cs]
set_property PACKAGE_PIN J2 [get_ports pi_ext_ad2_sdata]
set_property PACKAGE_PIN G1 [get_ports {po2_pfc_pwm[1]}]
set_property PACKAGE_PIN A4 [get_ports {po2_pfc_pwm[0]}]
set_property PACKAGE_PIN P3 [get_ports {po2_ht_pri_pwm[1]}]
set_property PACKAGE_PIN N4 [get_ports {po2_ht_pri_pwm[0]}]
set_property PACKAGE_PIN L3 [get_ports {po2_ht_sec_pwm[1]}]
set_property PACKAGE_PIN M2 [get_ports {po2_ht_sec_pwm[0]}]
set_property PACKAGE_PIN P5 [get_ports {po2_DHB_pri_pwm[0]}]
set_property PACKAGE_PIN P4 [get_ports {po2_DHB_pri_pwm[1]}]
set_property PACKAGE_PIN M1 [get_ports {po2_DHB_sec_pwm[1]}]
set_property PACKAGE_PIN N1 [get_ports {po2_DHB_sec_pwm[0]}]




# User Generated physical constraints





# User Generated physical constraints 

set_property PACKAGE_PIN J12 [get_ports {po3_led2[1]}]
set_property PACKAGE_PIN H14 [get_ports {po3_led2[0]}]

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
