# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/tcl/tube_psu_s6.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/tcl/tube_psu_s6.srcs/sources_1/ip/clk_wiz_v3_6_0/coregen.cgc"

set ipFile "c:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/tcl/tube_psu_s6.srcs/sources_1/ip/clk_wiz_v3_6_0/clk_wiz_v3_6_0.xco"

set ipName "clk_wiz_v3_6_0"

set vlnv "xilinx.com:ip:clk_wiz:3.6"

set cgPartSpec "xc6slx16-3ftg256"

set bomFilePath "c:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/tcl/tube_psu_s6.srcs/sources_1/ip/clk_wiz_v3_6_0/pa_cg_bom.xml"

set hdlType "Verilog"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

# configure the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_config_core.tcl"]

exit $result

