# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/tcl/tube_psu_s6.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/ip/clk_wiz_v3_6_0/coregen.cgc"

set ipFile "c:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/ip/clk_wiz_v3_6_0/system_clocks.xco"

set ipName "system_clocks"

set hdlType "Verilog"

set cgPartSpec "xc6slx16-3ftg256"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "c:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/ip/clk_wiz_v3_6_0/pa_cg_bom.xml"

# generate the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

