# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories true

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/tcl/tube_psu_s6.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/tcl/tube_psu_s6.srcs/sources_1/ip/mult_gen_v11_2_0/coregen.cgc"

set ipFile "c:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/tcl/tube_psu_s6.srcs/sources_1/ip/mult_gen_v11_2_0/mult_gen_v11_2_0.xco"

set ipName "mult_gen_v11_2_0"

set vlnv "xilinx.com:ip:mult_gen:11.2"

set cgPartSpec "xc6slx16-3ftg256"

set bomFilePath "c:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/tcl/tube_psu_s6.srcs/sources_1/ip/mult_gen_v11_2_0/pa_cg_bom.xml"

set hdlType "Verilog"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

# configure the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_config_core.tcl"]

exit $result

