# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories true

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/tcl/tube_psu_s6.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/ip/mult_gen_v11_2_0/coregen.cgc"

set ipFile "c:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/ip/mult_gen_v11_2_0/mult_sign18x18.xco"

set ipName "mult_sign18x18"

set hdlType "Verilog"

set cgPartSpec "xc6slx16-3ftg256"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "c:/Users/U376541/mycodeprojects/tube_power_v5/spartan_6/ip/mult_gen_v11_2_0/pa_cg_bom.xml"

# generate the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

