-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4
-- Module  Version: 4.9
--C:\Programs\diamond\diamond\3.11_x64\ispfpga\bin\nt64\scuba.exe -w -n pipelined_multiplier -lang vhdl -synth synplify -bus_exp 7 -bb -arch sa5p00 -type dspmult -simple_portname -widtha 18 -widthb 18 -widthp 36 -signed -PL_stages 1 -clk0 -ce0 -rst0 -fdc C:/Users/Jari/mycodeprojects/tube_psu/lfe5u/ecp5u_specifics/ecp5_ip_components/pipelined_multiplier/pipelined_multiplier.fdc 

-- Mon Jul 22 08:12:06 2019

library IEEE;
use IEEE.std_logic_1164.all;
library ECP5U;
use ECP5U.components.all;

entity pipelined_multiplier is
    port (
        Clock: in  std_logic; 
        ClkEn: in  std_logic; 
        Aclr: in  std_logic; 
        DataA: in  std_logic_vector(17 downto 0); 
        DataB: in  std_logic_vector(17 downto 0); 
        Result: out  std_logic_vector(35 downto 0));
end pipelined_multiplier;

architecture Structure of pipelined_multiplier is

    -- internal signal declarations
    signal pipelined_multiplier_mult_direct_out_1_35: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_34: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_33: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_32: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_31: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_30: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_29: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_28: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_27: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_26: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_25: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_24: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_23: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_22: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_21: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_20: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_19: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_18: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_17: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_16: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_15: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_14: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_13: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_12: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_11: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_10: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_9: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_8: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_7: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_6: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_5: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_4: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_3: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_2: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_1: std_logic;
    signal pipelined_multiplier_mult_direct_out_1_0: std_logic;
    signal scuba_vhi: std_logic;
    signal scuba_vlo: std_logic;

    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    dsp_mult_0: MULT18X18D
        generic map (CLK3_DIV=> "ENABLED", CLK2_DIV=> "ENABLED", 
        CLK1_DIV=> "ENABLED", CLK0_DIV=> "ENABLED", HIGHSPEED_CLK=> "NONE", 
        REG_INPUTC_RST=> "RST0", REG_INPUTC_CE=> "CE0", REG_INPUTC_CLK=> "NONE", 
        SOURCEB_MODE=> "B_SHIFT", MULT_BYPASS=> "DISABLED", 
        CAS_MATCH_REG=> "FALSE", RESETMODE=> "ASYNC", GSR=> "ENABLED", 
        REG_OUTPUT_RST=> "RST0", REG_OUTPUT_CE=> "CE0", REG_OUTPUT_CLK=> "NONE", 
        REG_PIPELINE_RST=> "RST0", REG_PIPELINE_CE=> "CE0", 
        REG_PIPELINE_CLK=> "CLK0", REG_INPUTB_RST=> "RST0", 
        REG_INPUTB_CE=> "CE0", REG_INPUTB_CLK=> "NONE", REG_INPUTA_RST=> "RST0", 
        REG_INPUTA_CE=> "CE0", REG_INPUTA_CLK=> "NONE")
        port map (A17=>DataA(17), A16=>DataA(16), A15=>DataA(15), 
            A14=>DataA(14), A13=>DataA(13), A12=>DataA(12), 
            A11=>DataA(11), A10=>DataA(10), A9=>DataA(9), A8=>DataA(8), 
            A7=>DataA(7), A6=>DataA(6), A5=>DataA(5), A4=>DataA(4), 
            A3=>DataA(3), A2=>DataA(2), A1=>DataA(1), A0=>DataA(0), 
            B17=>DataB(17), B16=>DataB(16), B15=>DataB(15), 
            B14=>DataB(14), B13=>DataB(13), B12=>DataB(12), 
            B11=>DataB(11), B10=>DataB(10), B9=>DataB(9), B8=>DataB(8), 
            B7=>DataB(7), B6=>DataB(6), B5=>DataB(5), B4=>DataB(4), 
            B3=>DataB(3), B2=>DataB(2), B1=>DataB(1), B0=>DataB(0), 
            C17=>scuba_vlo, C16=>scuba_vlo, C15=>scuba_vlo, 
            C14=>scuba_vlo, C13=>scuba_vlo, C12=>scuba_vlo, 
            C11=>scuba_vlo, C10=>scuba_vlo, C9=>scuba_vlo, C8=>scuba_vlo, 
            C7=>scuba_vlo, C6=>scuba_vlo, C5=>scuba_vlo, C4=>scuba_vlo, 
            C3=>scuba_vlo, C2=>scuba_vlo, C1=>scuba_vlo, C0=>scuba_vlo, 
            SIGNEDA=>scuba_vhi, SIGNEDB=>scuba_vhi, SOURCEA=>scuba_vlo, 
            SOURCEB=>scuba_vlo, CE0=>ClkEn, CE1=>scuba_vhi, 
            CE2=>scuba_vhi, CE3=>scuba_vhi, CLK0=>Clock, CLK1=>scuba_vlo, 
            CLK2=>scuba_vlo, CLK3=>scuba_vlo, RST0=>Aclr, 
            RST1=>scuba_vlo, RST2=>scuba_vlo, RST3=>scuba_vlo, 
            SRIA17=>scuba_vlo, SRIA16=>scuba_vlo, SRIA15=>scuba_vlo, 
            SRIA14=>scuba_vlo, SRIA13=>scuba_vlo, SRIA12=>scuba_vlo, 
            SRIA11=>scuba_vlo, SRIA10=>scuba_vlo, SRIA9=>scuba_vlo, 
            SRIA8=>scuba_vlo, SRIA7=>scuba_vlo, SRIA6=>scuba_vlo, 
            SRIA5=>scuba_vlo, SRIA4=>scuba_vlo, SRIA3=>scuba_vlo, 
            SRIA2=>scuba_vlo, SRIA1=>scuba_vlo, SRIA0=>scuba_vlo, 
            SRIB17=>scuba_vlo, SRIB16=>scuba_vlo, SRIB15=>scuba_vlo, 
            SRIB14=>scuba_vlo, SRIB13=>scuba_vlo, SRIB12=>scuba_vlo, 
            SRIB11=>scuba_vlo, SRIB10=>scuba_vlo, SRIB9=>scuba_vlo, 
            SRIB8=>scuba_vlo, SRIB7=>scuba_vlo, SRIB6=>scuba_vlo, 
            SRIB5=>scuba_vlo, SRIB4=>scuba_vlo, SRIB3=>scuba_vlo, 
            SRIB2=>scuba_vlo, SRIB1=>scuba_vlo, SRIB0=>scuba_vlo, 
            SROA17=>open, SROA16=>open, SROA15=>open, SROA14=>open, 
            SROA13=>open, SROA12=>open, SROA11=>open, SROA10=>open, 
            SROA9=>open, SROA8=>open, SROA7=>open, SROA6=>open, 
            SROA5=>open, SROA4=>open, SROA3=>open, SROA2=>open, 
            SROA1=>open, SROA0=>open, SROB17=>open, SROB16=>open, 
            SROB15=>open, SROB14=>open, SROB13=>open, SROB12=>open, 
            SROB11=>open, SROB10=>open, SROB9=>open, SROB8=>open, 
            SROB7=>open, SROB6=>open, SROB5=>open, SROB4=>open, 
            SROB3=>open, SROB2=>open, SROB1=>open, SROB0=>open, 
            ROA17=>open, ROA16=>open, ROA15=>open, ROA14=>open, 
            ROA13=>open, ROA12=>open, ROA11=>open, ROA10=>open, 
            ROA9=>open, ROA8=>open, ROA7=>open, ROA6=>open, ROA5=>open, 
            ROA4=>open, ROA3=>open, ROA2=>open, ROA1=>open, ROA0=>open, 
            ROB17=>open, ROB16=>open, ROB15=>open, ROB14=>open, 
            ROB13=>open, ROB12=>open, ROB11=>open, ROB10=>open, 
            ROB9=>open, ROB8=>open, ROB7=>open, ROB6=>open, ROB5=>open, 
            ROB4=>open, ROB3=>open, ROB2=>open, ROB1=>open, ROB0=>open, 
            ROC17=>open, ROC16=>open, ROC15=>open, ROC14=>open, 
            ROC13=>open, ROC12=>open, ROC11=>open, ROC10=>open, 
            ROC9=>open, ROC8=>open, ROC7=>open, ROC6=>open, ROC5=>open, 
            ROC4=>open, ROC3=>open, ROC2=>open, ROC1=>open, ROC0=>open, 
            P35=>pipelined_multiplier_mult_direct_out_1_35, 
            P34=>pipelined_multiplier_mult_direct_out_1_34, 
            P33=>pipelined_multiplier_mult_direct_out_1_33, 
            P32=>pipelined_multiplier_mult_direct_out_1_32, 
            P31=>pipelined_multiplier_mult_direct_out_1_31, 
            P30=>pipelined_multiplier_mult_direct_out_1_30, 
            P29=>pipelined_multiplier_mult_direct_out_1_29, 
            P28=>pipelined_multiplier_mult_direct_out_1_28, 
            P27=>pipelined_multiplier_mult_direct_out_1_27, 
            P26=>pipelined_multiplier_mult_direct_out_1_26, 
            P25=>pipelined_multiplier_mult_direct_out_1_25, 
            P24=>pipelined_multiplier_mult_direct_out_1_24, 
            P23=>pipelined_multiplier_mult_direct_out_1_23, 
            P22=>pipelined_multiplier_mult_direct_out_1_22, 
            P21=>pipelined_multiplier_mult_direct_out_1_21, 
            P20=>pipelined_multiplier_mult_direct_out_1_20, 
            P19=>pipelined_multiplier_mult_direct_out_1_19, 
            P18=>pipelined_multiplier_mult_direct_out_1_18, 
            P17=>pipelined_multiplier_mult_direct_out_1_17, 
            P16=>pipelined_multiplier_mult_direct_out_1_16, 
            P15=>pipelined_multiplier_mult_direct_out_1_15, 
            P14=>pipelined_multiplier_mult_direct_out_1_14, 
            P13=>pipelined_multiplier_mult_direct_out_1_13, 
            P12=>pipelined_multiplier_mult_direct_out_1_12, 
            P11=>pipelined_multiplier_mult_direct_out_1_11, 
            P10=>pipelined_multiplier_mult_direct_out_1_10, 
            P9=>pipelined_multiplier_mult_direct_out_1_9, 
            P8=>pipelined_multiplier_mult_direct_out_1_8, 
            P7=>pipelined_multiplier_mult_direct_out_1_7, 
            P6=>pipelined_multiplier_mult_direct_out_1_6, 
            P5=>pipelined_multiplier_mult_direct_out_1_5, 
            P4=>pipelined_multiplier_mult_direct_out_1_4, 
            P3=>pipelined_multiplier_mult_direct_out_1_3, 
            P2=>pipelined_multiplier_mult_direct_out_1_2, 
            P1=>pipelined_multiplier_mult_direct_out_1_1, 
            P0=>pipelined_multiplier_mult_direct_out_1_0, SIGNEDP=>open);

    Result(35) <= pipelined_multiplier_mult_direct_out_1_35;
    Result(34) <= pipelined_multiplier_mult_direct_out_1_34;
    Result(33) <= pipelined_multiplier_mult_direct_out_1_33;
    Result(32) <= pipelined_multiplier_mult_direct_out_1_32;
    Result(31) <= pipelined_multiplier_mult_direct_out_1_31;
    Result(30) <= pipelined_multiplier_mult_direct_out_1_30;
    Result(29) <= pipelined_multiplier_mult_direct_out_1_29;
    Result(28) <= pipelined_multiplier_mult_direct_out_1_28;
    Result(27) <= pipelined_multiplier_mult_direct_out_1_27;
    Result(26) <= pipelined_multiplier_mult_direct_out_1_26;
    Result(25) <= pipelined_multiplier_mult_direct_out_1_25;
    Result(24) <= pipelined_multiplier_mult_direct_out_1_24;
    Result(23) <= pipelined_multiplier_mult_direct_out_1_23;
    Result(22) <= pipelined_multiplier_mult_direct_out_1_22;
    Result(21) <= pipelined_multiplier_mult_direct_out_1_21;
    Result(20) <= pipelined_multiplier_mult_direct_out_1_20;
    Result(19) <= pipelined_multiplier_mult_direct_out_1_19;
    Result(18) <= pipelined_multiplier_mult_direct_out_1_18;
    Result(17) <= pipelined_multiplier_mult_direct_out_1_17;
    Result(16) <= pipelined_multiplier_mult_direct_out_1_16;
    Result(15) <= pipelined_multiplier_mult_direct_out_1_15;
    Result(14) <= pipelined_multiplier_mult_direct_out_1_14;
    Result(13) <= pipelined_multiplier_mult_direct_out_1_13;
    Result(12) <= pipelined_multiplier_mult_direct_out_1_12;
    Result(11) <= pipelined_multiplier_mult_direct_out_1_11;
    Result(10) <= pipelined_multiplier_mult_direct_out_1_10;
    Result(9) <= pipelined_multiplier_mult_direct_out_1_9;
    Result(8) <= pipelined_multiplier_mult_direct_out_1_8;
    Result(7) <= pipelined_multiplier_mult_direct_out_1_7;
    Result(6) <= pipelined_multiplier_mult_direct_out_1_6;
    Result(5) <= pipelined_multiplier_mult_direct_out_1_5;
    Result(4) <= pipelined_multiplier_mult_direct_out_1_4;
    Result(3) <= pipelined_multiplier_mult_direct_out_1_3;
    Result(2) <= pipelined_multiplier_mult_direct_out_1_2;
    Result(1) <= pipelined_multiplier_mult_direct_out_1_1;
    Result(0) <= pipelined_multiplier_mult_direct_out_1_0;
end Structure;
