-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.3.144
-- Module  Version: 5.7
-- Sat May 18 08:57:35 2019

-- parameterized module component declaration
component main_pll
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; CLKOS2: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : main_pll
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__, CLKOS2=>__, LOCK=>__);
